EXP:
  NAME: 'msnet_v1'
MODEL:
  NAME: "MSNetV1"
  DEVICE: "cuda"
  PARALLEL: True
  DEVICE_IDS: []
DATASET:
  TRAIN: "COCO.train"
  VAL: "HPATCHES_VIEWPOINT.val"
  TEST: "HPATCHES_VIEWPOINT.all"
  COCO:
    WIDTH: 320
    HEIGHT: 240
    KPS: 3000
  HPATCHES:
    SIZE: 640
    KPS: 1000
TRAIN:
  RESUME: True
  CHECKPOINT_PERIOD: 1000
  BATCH_SIZE: 1
  MAX_EPOCHS: 3
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.0005
  VAL_EVERY: 1000
TEST:
  BATCH_SIZE: 1
  PCK_THRESHOLD: 5
  EVALUATOR: 'DESC_PCK'
VAL:
  IS_ON: True
  BATCH_SIZE: 1
  EVALUATOR: 'DESC_PCK'
  PCK_THRESHOLD: 5

TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", 'distance', 'similarity', 'val_result']
    IMAGE: ['imgs', 'descs', 'corr', 'corr_false']
