EXP:
  NAME: 'test'
MODEL:
  NAME: "MSNetV0"
  DEVICE: "cuda"
  PARALLEL: True
DATASET:
  TRAIN: "COCO.train"
  TEST: "HPATCHES_VIEWPOINT"
  VAL: "COCO.test"
  COCO:
    WIDTH: 320
    HEIGHT: 240
    KPS: 3000
  HPATCHES:
    SIZE: 640
    KPS: 1000
TRAIN:
  RESUME: True
  CHECKPOINT_PERIOD: 1000
  BATCH_SIZE: 1
  MAX_EPOCHS: 2
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.0005
TEST:
  BATCH_SIZE: 1
  PCK_THRESHOLD: 5
  EVALUATOR: 'DESC_PCK'

TENSORBOARD:
  IS_ON: True
  TARGETS:
    SCALAR: ["loss", 'distance', 'similarity']
    IMAGE: ['imgs', 'descs', 'corr', 'corr_false']
